#!/usr/bin/env bash
# generate-project-tree.sh
# Regenerates project-tree.txt with the current directory structure.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$REPO_ROOT/project-tree.txt"

echo "Generating project tree -> $OUTPUT"

{
  echo "Project tree (auto-generated by scripts/generate-project-tree.sh):"
  echo ""
  # Use find to list directories and files, excluding .git and hidden dirs
  find "$REPO_ROOT" \
    -not -path '*/.git/*' \
    -not -name '.git' \
    -not -path '*/node_modules/*' \
    | sort \
    | sed "s|$REPO_ROOT/||" \
    | grep -v '^$' \
    | awk '{
        depth = gsub(/\//, "/")
        indent = ""
        for (i=0; i<depth; i++) indent = indent "  "
        # Print only the basename
        n = split($0, parts, "/")
        print indent "- " parts[n]
      }'
} > "$OUTPUT"

echo "Done. Written to $OUTPUT"